FROM debian:bookworm-slim
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y --no-install-recommends \
      nftables iproute2 iputils-ping traceroute curl netcat-openbsd \
      nmap hping3 tcpdump python3 \
    && rm -rf /var/lib/apt/lists/*
